### PR TITLE
:bug: fix: resolve the git-sync image in the documentation and reformat the docker-compose file to yaml

### LINKED ISSUE #15: resolve project_data/dags directory which is mounted in common-airflow
Revise the path that should be mounted to the Airflow containers. Maybe `dags` is wrong in `project_data/dags` path.

### PR DESCRIPTION
**Pull request by imans777**

### CODE REVIEW

**Review by mostafa-cerestech — APPROVED** [review]
Wow, look who is here. :)))))))
Thank you for valuable contribution, Iman! <3

**Review by mostafa-cerestech — COMMENTED** [review]
perfect

**Review by mostafaghadimi — APPROVED** [review]
Wow, look who’s here! =) 
Thank you, Iman, for your invaluable contribution. You are still precise.

**Comment by imans777** [comment]
It's really a small world =) <3

**Comment by mostafaghadimi** [comment]
Well done, @imans777 jan. It's really nice to hearing from you.

**Pull request merged**
